import roblox from '../../assets/img/roblox.jpg';
import friend from '../../assets/img/my-friend.jpg';
import blue from '../../assets/img/blue.jpg'
import fire from '../../assets/img/fire.jpg';
import cloud from '../../assets/img/cloud.jpg';
export const Games=[
    {
        name:'Roblox',
        intro:'Roblox is a vast online platform where kids can create and interact in what its makers describe as "immersive 3D worlds." Players are given the opportunity to create an avatar (player) for themselves and allotted a small amount of digital money to rent a house. Money to furnish and decorate the house requires real world money, with costs adding up fast. A variety of different outfits are also available to purchase which is a huge drawcard for many young children who want to make their avatar look as cool as possible. Players who don’t buy upgrades  may be mocked by other players and pressured into spending more.',
        img:roblox,
        age:"Available on smartphones, tablets, desktop computers, the Xbox One, and some VR headsets, Roblox has an ESRB rating of E10+ for Everyone 10 and up for Fantasy Violence, which means that typical gameplay should be suitable for most kids. However, the rating also includes a Users Interact notice, warning parents that players can communicate with each other, join groups and create and share games with each other. In fact, your child can even sell their game on Roblox! Although Roblox proactively monitors the content created on its platform, with 70 million active users a month some offensive communications or user-generated content may slip through the cracks. So, it’s important for parents to familiarize themselves with the robust parental controls that Roblox provides (more on that below) to ensure their children are shielded from inappropriate content or communications.",
        parent:"First and foremost, make sure that your child’s registration in Roblox includes an accurate birthdate! This will enable automatic filtering and other protections specifically designed to protect children under the age of 13. Being that Roblox primarily consists of user-created content, the Roblox team has integrated a variety of parental controls directly into its Settings, which is further explored in its Parent’s Guide. Roblox’s parental controls give parents the ability to curate the content their kids may encounter when playing, including options to restrict voice chat only to approved friends or turn it off entirely, create a white list of age-appropriate games for your kids, and more. You can learn how to enable those controls here.But that’s not all! Roblox also allows your child to block and report annoying or disruptive players. Make sure they (and you) know how to do so. Of course, this also creates an opportunity to have a discussion about online etiquette, which frankly shouldn’t be all that different than how you teach them to behave off-line! “Do unto others as you would have them do unto you” goes a long way. Another basic internet safety rule is to never share personal information or passwords online. No matter what. Concerned about the amount of time or money your child spends playing Roblox? Whichever device your child uses to play Roblox, there are a variety of settings you can activate, including restrictions on how much money your child can spend. Some parental tools like Microsoft’s Family Settings, Apple’s Screen Time and Google’s Family Link provide the ability to control exactly when or how long your child is permitted to play games to make sure they get their homework done or don’t stay up past their bedtime playing Roblox!"
        
    },
    {
        name:'My Friend Cayla',
        intro:'Roblox is a vast online platform where kids can create and interact in what its makers describe as "immersive 3D worlds." Players are given the opportunity to create an avatar (player) for themselves and allotted a small amount of digital money to rent a house. Money to furnish and decorate the house requires real world money, with costs adding up fast. A variety of different outfits are also available to purchase which is a huge drawcard for many young children who want to make their avatar look as cool as possible. Players who don’t buy upgrades  may be mocked by other players and pressured into spending more.',
        img:friend,
        age:"Available on smartphones, tablets, desktop computers, the Xbox One, and some VR headsets, Roblox has an ESRB rating of E10+ for Everyone 10 and up for Fantasy Violence, which means that typical gameplay should be suitable for most kids. However, the rating also includes a Users Interact notice, warning parents that players can communicate with each other, join groups and create and share games with each other. In fact, your child can even sell their game on Roblox! Although Roblox proactively monitors the content created on its platform, with 70 million active users a month some offensive communications or user-generated content may slip through the cracks. So, it’s important for parents to familiarize themselves with the robust parental controls that Roblox provides (more on that below) to ensure their children are shielded from inappropriate content or communications.",
        parent:"First and foremost, make sure that your child’s registration in Roblox includes an accurate birthdate! This will enable automatic filtering and other protections specifically designed to protect children under the age of 13. Being that Roblox primarily consists of user-created content, the Roblox team has integrated a variety of parental controls directly into its Settings, which is further explored in its Parent’s Guide. Roblox’s parental controls give parents the ability to curate the content their kids may encounter when playing, including options to restrict voice chat only to approved friends or turn it off entirely, create a white list of age-appropriate games for your kids, and more. You can learn how to enable those controls here.But that’s not all! Roblox also allows your child to block and report annoying or disruptive players. Make sure they (and you) know how to do so. Of course, this also creates an opportunity to have a discussion about online etiquette, which frankly shouldn’t be all that different than how you teach them to behave off-line! “Do unto others as you would have them do unto you” goes a long way. Another basic internet safety rule is to never share personal information or passwords online. No matter what. Concerned about the amount of time or money your child spends playing Roblox? Whichever device your child uses to play Roblox, there are a variety of settings you can activate, including restrictions on how much money your child can spend. Some parental tools like Microsoft’s Family Settings, Apple’s Screen Time and Google’s Family Link provide the ability to control exactly when or how long your child is permitted to play games to make sure they get their homework done or don’t stay up past their bedtime playing Roblox!",         
    },
    {
        name:'Blue Whale',
        intro:'Roblox is a vast online platform where kids can create and interact in what its makers describe as "immersive 3D worlds." Players are given the opportunity to create an avatar (player) for themselves and allotted a small amount of digital money to rent a house. Money to furnish and decorate the house requires real world money, with costs adding up fast. A variety of different outfits are also available to purchase which is a huge drawcard for many young children who want to make their avatar look as cool as possible. Players who don’t buy upgrades  may be mocked by other players and pressured into spending more.',
        img:blue,
        age:"Available on smartphones, tablets, desktop computers, the Xbox One, and some VR headsets, Roblox has an ESRB rating of E10+ for Everyone 10 and up for Fantasy Violence, which means that typical gameplay should be suitable for most kids. However, the rating also includes a Users Interact notice, warning parents that players can communicate with each other, join groups and create and share games with each other. In fact, your child can even sell their game on Roblox! Although Roblox proactively monitors the content created on its platform, with 70 million active users a month some offensive communications or user-generated content may slip through the cracks. So, it’s important for parents to familiarize themselves with the robust parental controls that Roblox provides (more on that below) to ensure their children are shielded from inappropriate content or communications.",
        parent:"First and foremost, make sure that your child’s registration in Roblox includes an accurate birthdate! This will enable automatic filtering and other protections specifically designed to protect children under the age of 13. Being that Roblox primarily consists of user-created content, the Roblox team has integrated a variety of parental controls directly into its Settings, which is further explored in its Parent’s Guide. Roblox’s parental controls give parents the ability to curate the content their kids may encounter when playing, including options to restrict voice chat only to approved friends or turn it off entirely, create a white list of age-appropriate games for your kids, and more. You can learn how to enable those controls here. But that’s not all! Roblox also allows your child to block and report annoying or disruptive players. Make sure they (and you) know how to do so. Of course, this also creates an opportunity to have a discussion about online etiquette, which frankly shouldn’t be all that different than how you teach them to behave off-line! “Do unto others as you would have them do unto you” goes a long way. Another basic internet safety rule is to never share personal information or passwords online. No matter what. Concerned about the amount of time or money your child spends playing Roblox? Whichever device your child uses to play Roblox, there are a variety of settings you can activate, including restrictions on how much money your child can spend. Some parental tools like Microsoft’s Family Settings, Apple’s Screen Time and Google’s Family Link provide the ability to control exactly when or how long your child is permitted to play games to make sure they get their homework done or don’t stay up past their bedtime playing Roblox!",
        
    },
    {
        name:'Fire Fairy',
        intro:'Roblox is a vast online platform where kids can create and interact in what its makers describe as "immersive 3D worlds." Players are given the opportunity to create an avatar (player) for themselves and allotted a small amount of digital money to rent a house. Money to furnish and decorate the house requires real world money, with costs adding up fast. A variety of different outfits are also available to purchase which is a huge drawcard for many young children who want to make their avatar look as cool as possible. Players who don’t buy upgrades  may be mocked by other players and pressured into spending more.',
        img:fire,
        age:"Available on smartphones, tablets, desktop computers, the Xbox One, and some VR headsets, Roblox has an ESRB rating of E10+ for Everyone 10 and up for Fantasy Violence, which means that typical gameplay should be suitable for most kids. However, the rating also includes a Users Interact notice, warning parents that players can communicate with each other, join groups and create and share games with each other. In fact, your child can even sell their game on Roblox! Although Roblox proactively monitors the content created on its platform, with 70 million active users a month some offensive communications or user-generated content may slip through the cracks. So, it’s important for parents to familiarize themselves with the robust parental controls that Roblox provides (more on that below) to ensure their children are shielded from inappropriate content or communications.",
        parent:"First and foremost, make sure that your child’s registration in Roblox includes an accurate birthdate! This will enable automatic filtering and other protections specifically designed to protect children under the age of 13. Being that Roblox primarily consists of user-created content, the Roblox team has integrated a variety of parental controls directly into its Settings, which is further explored in its Parent’s Guide. Roblox’s parental controls give parents the ability to curate the content their kids may encounter when playing, including options to restrict voice chat only to approved friends or turn it off entirely, create a white list of age-appropriate games for your kids, and more. You can learn how to enable those controls here. But that’s not all! Roblox also allows your child to block and report annoying or disruptive players. Make sure they (and you) know how to do so. Of course, this also creates an opportunity to have a discussion about online etiquette, which frankly shouldn’t be all that different than how you teach them to behave off-line! “Do unto others as you would have them do unto you” goes a long way. Another basic internet safety rule is to never share personal information or passwords online. No matter what. Concerned about the amount of time or money your child spends playing Roblox? Whichever device your child uses to play Roblox, there are a variety of settings you can activate, including restrictions on how much money your child can spend. Some parental tools like Microsoft’s Family Settings, Apple’s Screen Time and Google’s Family Link provide the ability to control exactly when or how long your child is permitted to play games to make sure they get their homework done or don’t stay up past their bedtime playing Roblox!",
    },
    {
        name:'Cloud Pets',
        intro:'Roblox is a vast online platform where kids can create and interact in what its makers describe as "immersive 3D worlds." Players are given the opportunity to create an avatar (player) for themselves and allotted a small amount of digital money to rent a house. Money to furnish and decorate the house requires real world money, with costs adding up fast. A variety of different outfits are also available to purchase which is a huge drawcard for many young children who want to make their avatar look as cool as possible. Players who don’t buy upgrades  may be mocked by other players and pressured into spending more.',
        img:cloud,
        age:"Available on smartphones, tablets, desktop computers, the Xbox One, and some VR headsets, Roblox has an ESRB rating of E10+ for Everyone 10 and up for Fantasy Violence, which means that typical gameplay should be suitable for most kids. However, the rating also includes a Users Interact notice, warning parents that players can communicate with each other, join groups and create and share games with each other. In fact, your child can even sell their game on Roblox! Although Roblox proactively monitors the content created on its platform, with 70 million active users a month some offensive communications or user-generated content may slip through the cracks. So, it’s important for parents to familiarize themselves with the robust parental controls that Roblox provides (more on that below) to ensure their children are shielded from inappropriate content or communications.",
        parent:"First and foremost, make sure that your child’s registration in Roblox includes an accurate birthdate! This will enable automatic filtering and other protections specifically designed to protect children under the age of 13. Being that Roblox primarily consists of user-created content, the Roblox team has integrated a variety of parental controls directly into its Settings, which is further explored in its Parent’s Guide. Roblox’s parental controls give parents the ability to curate the content their kids may encounter when playing, including options to restrict voice chat only to approved friends or turn it off entirely, create a white list of age-appropriate games for your kids, and more. You can learn how to enable those controls here. But that’s not all! Roblox also allows your child to block and report annoying or disruptive players. Make sure they (and you) know how to do so. Of course, this also creates an opportunity to have a discussion about online etiquette, which frankly shouldn’t be all that different than how you teach them to behave off-line! “Do unto others as you would have them do unto you” goes a long way. Another basic internet safety rule is to never share personal information or passwords online. No matter what. Concerned about the amount of time or money your child spends playing Roblox? Whichever device your child uses to play Roblox, there are a variety of settings you can activate, including restrictions on how much money your child can spend. Some parental tools like Microsoft’s Family Settings, Apple’s Screen Time and Google’s Family Link provide the ability to control exactly when or how long your child is permitted to play games to make sure they get their homework done or don’t stay up past their bedtime playing Roblox!",
    }
]